# Generated by Django 2.2.7 on 2020-05-08 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('distributors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimateNumber', models.CharField(max_length=200)),
                ('serialNo', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('pricePerUnit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('delivered', models.CharField(blank=True, default='No', max_length=20)),
                ('qty', models.PositiveIntegerField()),
                ('markup', models.PositiveIntegerField()),
                ('totalInvestment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('srp', models.DecimalField(decimal_places=2, max_digits=20)),
                ('newSRPPerUnit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalNonTax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('taxPerUnit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalTaxPerLot', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalWithTaxPerUnit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalWithTax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productprofit_distributor', to='distributors.Distributor')),
                ('productCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productprofit_productcode', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimateNumber', models.CharField(max_length=200)),
                ('projectName', models.CharField(max_length=200)),
                ('overallInvestment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('overallNonTax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('overallTaxPerLot', models.DecimalField(decimal_places=2, max_digits=20)),
                ('overallWithTaxPerUnit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('overallWithTax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('overallProfit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Successful', 'Successful')], default='Pending', max_length=50)),
                ('quotationNotes', models.TextField(blank=True, max_length=500)),
                ('invoiceNotes', models.TextField(blank=True, max_length=500)),
                ('poNotes', models.TextField(blank=True, max_length=500)),
                ('modeOfPayment', models.PositiveIntegerField()),
                ('nonVatLabel', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('completedDate', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_customer', to='customers.Customer')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('export_estimate', 'Can export estimate data as excel file')],
            },
        ),
    ]
